# Name: Jacky Si Long Jun
# GUID: 2427249S
# Date: 10/4/2020
name:                cw-scraper
version:             0.1.0.0
github:              "jeremysinger/cw-scraper"
license:             BSD3
author:              "Jeremy Singer"
maintainer:          "Jeremy.Singer@glasgow.ac.uk"
copyright:           "2019 Jeremy Singer"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Coursework for FP(H) - wikipedia web scraper
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeremysinger/cw-scraper#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- split

library:
  source-dirs: src

executables:
  cw-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw-scraper

tests:
  cw-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw-scraper
    - tasty
    - tasty-hunit
